import type { Metadata } from 'next'
import Link from 'next/link' // 👈 关键：引入 Next.js 专用链接组件
import './globals.css'

export const metadata: Metadata = {
  title: 'Notion CMS 知识库',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-CN">
      {/* 优化字体栈 */}
      <body className="min-h-screen bg-background font-sans antialiased">
        
        {/* === 顶部导航栏 (Navbar) === */}
        <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
          <div className="container flex h-14 max-w-6xl mx-auto items-center px-4 md:px-6">
            <div className="mr-4 flex">
              {/* 👇 修复点1：用 Link 替换 a */}
              <Link className="mr-6 flex items-center space-x-2 font-bold" href="/">
                <span>My Knowledge Base</span>
              </Link>
            </div>
            
            {/* 右侧菜单 */}
            <div className="flex flex-1 items-center justify-between space-x-2 md:justify-end">
              <nav className="flex items-center space-x-6 text-sm font-medium text-muted-foreground">
                {/* 👇 修复点2：用 Link 替换 a */}
                <Link href="/" className="transition-colors hover:text-foreground">首页</Link>
                <Link href="#" className="transition-colors hover:text-foreground">目录</Link>
                <Link href="#" className="transition-colors hover:text-foreground">关于</Link>
              </nav>
            </div>
          </div>
        </header>

        {children}
      </body>
    </html>
  )
}
